apiVersion: v1
appVersion: "0.21.0"
description: Kafka GUI for Apache Kafka to manage topics, topics data, consumers group, schema registry, connect and more...
name: akhq
version: 0.2.8
keywords:
  - kafka
  - confluent
  - gui
  - schema-registry
  - kafka-connect
home: https://akhq.io
icon: https://raw.githubusercontent.com/tchiotludo/akhq/master/client/src/images/logo_black.png
sources:
  - https://github.com/tchiotludo/akhq
maintainers:
  - name: tchiotludo
    email: tchiot.ludo@gmail.com
